Repository TeamOHJO/yanoljaProject-Backend, pull requests merged in 2023-11, with the labels that each got.

#4 [Feature] 로그백 설정 업데이트 및 ResponseDTO 추가
  build.gradle
  src/main/java/com/example/yanolja/domain/user/controller/EmailController.java
  src/main/java/com/example/yanolja/domain/user/controller/EmailControllerAdvice.java
  src/main/java/com/example/yanolja/domain/user/request/EmailRequest.java
  src/main/java/com/example/yanolja/domain/user/service/EmailService.java
  src/main/java/com/example/yanolja/global/config/EmailConfig.java
  src/main/java/com/example/yanolja/global/util/ResponseDTO.java
  src/main/resources/logback-spring.xml
Labels: enhancement

#8 [feat & refactor] 11.21 fe&be 회의 수정사항 반영 및 ResponseDTO에 맞게 코드 수정
  src/main/java/com/example/yanolja/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/AccommodationImages.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/AccommodationRoomImages.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/AccommodationRooms.java
  src/main/java/com/example/yanolja/domain/user/controller/UserController.java
  src/main/java/com/example/yanolja/domain/user/controller/UserControllerAdvice.java
  src/main/java/com/example/yanolja/domain/user/dto/CreateUserRequest.java
  src/main/java/com/example/yanolja/domain/user/dto/CreateUserResponse.java
  src/main/java/com/example/yanolja/domain/user/entity/User.java
  src/main/java/com/example/yanolja/domain/user/error/InvalidPhonenumberException.java
  src/main/java/com/example/yanolja/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/yanolja/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/yanolja/global/springsecurity/CustomAuthenticationFailureHandler.java
  src/main/java/com/example/yanolja/global/springsecurity/LogoutSuccessHandler.java
  src/main/java/com/example/yanolja/global/util/CustomResponseUtil.java
  src/main/java/com/example/yanolja/global/util/ResponseDTO.java
  src/test/http/signup.http
Labels: enhancement

#9 [Feature] 회원가입, 회원탈퇴, 이메일 인증 구현
  src/main/java/com/example/yanolja/domain/user/controller/EmailControllerAdvice.java
  src/main/java/com/example/yanolja/domain/user/controller/UserController.java
  src/main/java/com/example/yanolja/domain/user/controller/UserControllerAdvice.java
  src/main/java/com/example/yanolja/domain/user/dto/CreateUserRequest.java
  src/main/java/com/example/yanolja/domain/user/entity/User.java
  src/main/java/com/example/yanolja/domain/user/error/EmailDuplicateError.java
  src/main/java/com/example/yanolja/domain/user/error/InvalidPhonenumberException.java
  src/main/java/com/example/yanolja/domain/user/exception/EmailDuplicateError.java
  src/main/java/com/example/yanolja/domain/user/exception/InvalidEmailException.java
  src/main/java/com/example/yanolja/domain/user/exception/UserNotFoundException.java
  src/main/java/com/example/yanolja/domain/user/repository/UserRepository.java
  src/main/java/com/example/yanolja/domain/user/service/ScheduledTasks.java
  src/main/java/com/example/yanolja/domain/user/service/UserService.java
  src/main/java/com/example/yanolja/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/yanolja/global/exception/ApplicationException.java
  src/main/java/com/example/yanolja/global/exception/ErrorCode.java
  src/main/java/com/example/yanolja/global/exception/GlobalExceptionRestAdvice.java
Labels: refactor, feat

#12 [Feature] 숙소 좋아요 기능 구현
  src/main/java/com/example/yanolja/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/controller/AccommodationLikesAdvice.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/controller/AccommodationLikesController.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/dto/AccommodationLikesRequest.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/dto/AccommodationLikesResponse.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/entity/AccommodationLikes.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/exception/UserIdAndAccommodationIdNotFoundException.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/repository/AccommodationLikesRepository.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/service/AccommodationLikesService.java
  src/main/java/com/example/yanolja/domain/accommodationLikes/service/AccommodationLikesServiceImpl.java
  src/main/java/com/example/yanolja/domain/user/entity/User.java
  src/main/java/com/example/yanolja/global/exception/ErrorCode.java
  src/test/http/POST_likes.http
  src/test/http/USER/login.http
Labels: feat

#28 [Feature] 숙소, 방 상세조회 기능 구현
  src/main/java/com/example/yanolja/domain/accommodation/controller/AccommodationControllerAdvice.java
  src/main/java/com/example/yanolja/domain/accommodation/controller/AccommodationDetailController.java
  src/main/java/com/example/yanolja/domain/accommodation/dto/AccommodationDetailResponse.java
  src/main/java/com/example/yanolja/domain/accommodation/dto/RoomDetail.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/AccommodationRooms.java
  src/main/java/com/example/yanolja/domain/accommodation/exception/AccommodationNotFoundException.java
  src/main/java/com/example/yanolja/domain/accommodation/exception/RoomNotFoundException.java
  src/main/java/com/example/yanolja/domain/accommodation/repository/AccommodationRoomRepository.java
  src/main/java/com/example/yanolja/domain/accommodation/service/AccommodationDetailsService.java
  src/main/java/com/example/yanolja/domain/review/entity/Review.java
  src/main/java/com/example/yanolja/global/exception/ErrorCode.java
  src/test/http/AccomodationDetail/accomodationDetail.http
  src/test/http/AccomodationDetail/roomDetail.http
  src/test/http/BASKET/DELETE_basket.http
  src/test/http/BASKET/GET_basket.http
  src/test/http/BASKET/POST_basket.http
  src/test/http/LIKE/POST_likes.http
  src/test/http/RESERVATION/DELETE_reservation.http
  src/test/http/RESERVATION/GET_reservation_details.http
  src/test/http/RESERVATION/POST_reservation.http
Labels: refactor, feat, question

#42 Feature/#29 get public api data
  build.gradle
  src/main/java/com/example/yanolja/domain/accommodation/controller/AccommodationApiController.java
  src/main/java/com/example/yanolja/domain/accommodation/dto/IntegratedAccommodationDTO.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/Accommodation.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/AccommodationImages.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/AccommodationRoomImages.java
  src/main/java/com/example/yanolja/domain/accommodation/entity/AccommodationRooms.java
  src/main/java/com/example/yanolja/domain/accommodation/exception/ApiCallError.java
  src/main/java/com/example/yanolja/domain/accommodation/exception/ApiProcessingError.java
  src/main/java/com/example/yanolja/domain/accommodation/exception/JsonParsingError.java
  src/main/java/com/example/yanolja/domain/accommodation/service/AccommodationApiService.java
  src/main/java/com/example/yanolja/global/exception/ErrorCode.java
  src/main/java/com/example/yanolja/global/springsecurity/SpringSecurityConfig.java
  src/test/http/GET_fetch-API-Data.http
Labels: feat
